## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('messf', ['internet-stack'])
    module.source = [
        'messf.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'messf'
    headers.source = [
        'messf.h',
        'messf-helper.h',
        ]
