## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('secure-pingpong', ['internet-stack'])
    module.source = [
        'secure-pingpong.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'secure-pingpong'
    headers.source = [
        'secure-pingpong.h',
        'secure-pingpong-helper.h',
        ]
