## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('reachable2', ['internet-stack'])
    module.source = [
        'reachable2.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'reachable2'
    headers.source = [
        'reachable2.h',
        'reachable2-helper.h',
        ]
