## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('secure-pathvector', ['internet-stack'])
    module.source = [
        'secure-pathvector.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'secure-pathvector'
    headers.source = [
        'secure-pathvector.h',
        'secure-pathvector-helper.h',
        ]
