## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('epidemic', ['internet-stack'])
    module.source = [
        'epidemic.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'epidemic'
    headers.source = [
        'epidemic.h',
        'epidemic-helper.h',
        ]
