## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('acquaintance', ['internet-stack'])
    module.source = [
        'acquaintance.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'acquaintance'
    headers.source = [
        'acquaintance.h',
        'acquaintance-helper.h',
        ]
