## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('vqap-query', ['internet-stack'])
    module.source = [
        'vqap-query.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'vqap-query'
    headers.source = [
        'vqap-query.h',
        'vqap-query-helper.h',
        ]
