/* A RapidNet application. Generated by RapidNet compiler. */

#include "messf-query.h"
#include <cstdlib>
#include "ns3/nstime.h"
#include "ns3/simulator.h"
#include "ns3/type-ids.h"
#include "ns3/rapidnet-types.h"
#include "ns3/rapidnet-utils.h"
#include "ns3/assignor.h"
#include "ns3/selector.h"
#include "ns3/rapidnet-functions.h"

using namespace std;
using namespace ns3;
using namespace ns3::rapidnet;
using namespace ns3::rapidnet::messfquery;

const string MessfQuery::PRETURN = "pReturn";
const string MessfQuery::PERIODIC = "periodic";
const string MessfQuery::PROVQUERY = "provQuery";
const string MessfQuery::Q1_ECAPERIODIC = "q1_ecaperiodic";
const string MessfQuery::RECORDS = "records";
const string MessfQuery::RESULTS = "results";
const string MessfQuery::TUPLE = "tuple";

NS_LOG_COMPONENT_DEFINE ("MessfQuery");
NS_OBJECT_ENSURE_REGISTERED (MessfQuery);

TypeId
MessfQuery::GetTypeId (void)
{
  static TypeId tid = TypeId ("ns3::rapidnet::messfquery::MessfQuery")
    .SetParent<RapidNetApplicationBase> ()
    .AddConstructor<MessfQuery> ()
    ;
  return tid;
}

MessfQuery::MessfQuery()
{
  NS_LOG_FUNCTION_NOARGS ();
}

MessfQuery::~MessfQuery()
{
  NS_LOG_FUNCTION_NOARGS ();
}

void
MessfQuery::DoDispose (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::DoDispose ();
}

void
MessfQuery::StartApplication (void)
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StartApplication ();
  m_event_q1_ecaperiodic=
    Simulator::Schedule (Seconds (0), &MessfQuery::Q1_ecaperiodic, this);
  m_count_q1_ecaperiodic = 0;
  RAPIDNET_LOG_INFO("MessfQuery Application Started");
}

void
MessfQuery::StopApplication ()
{
  NS_LOG_FUNCTION_NOARGS ();

  RapidNetApplicationBase::StopApplication ();
  Simulator::Cancel(m_event_q1_ecaperiodic);
  RAPIDNET_LOG_INFO("MessfQuery Application Stopped");
}

void
MessfQuery::InitDatabase ()
{
  //RapidNetApplicationBase::InitDatabase ();

  AddRelationWithKeys (RECORDS, attrdeflist (
    attrdef ("records_attr1", IPV4),
    attrdef ("records_attr2", ID),
    attrdef ("records_attr3", ID)));

  AddRelationWithKeys (RESULTS, attrdeflist (
    attrdef ("results_attr1", IPV4),
    attrdef ("results_attr2", ID),
    attrdef ("results_attr3", ID)));

  AddRelationWithKeys (TUPLE, attrdeflist (
    attrdef ("tuple_attr1", IPV4),
    attrdef ("tuple_attr2", STR)));

}

void
MessfQuery::DemuxRecv (Ptr<Tuple> tuple)
{
  RapidNetApplicationBase::DemuxRecv (tuple);

  if (IsRecvEvent (tuple, Q1_ECAPERIODIC))
    {
      Q1_eca (tuple);
    }
  if (IsRecvEvent (tuple, PRETURN))
    {
      Q2_eca (tuple);
    }
  if (IsInsertEvent (tuple, RECORDS))
    {
      Q3Eca0Ins (tuple);
    }
  if (IsDeleteEvent (tuple, RECORDS))
    {
      Q3Eca0Del (tuple);
    }
}

void
MessfQuery::Q1_ecaperiodic ()
{
  RAPIDNET_LOG_INFO ("Q1_ecaperiodic triggered");

  SendLocal (tuple (Q1_ECAPERIODIC, attrlist (
    attr ("q1_ecaperiodic_attr1", Ipv4Value, GetAddress ()),
    attr ("q1_ecaperiodic_attr2", Int32Value, rand ()))));

  if (++m_count_q1_ecaperiodic < 2)
    {
      m_event_q1_ecaperiodic = Simulator::Schedule (Seconds(4),
        &MessfQuery::Q1_ecaperiodic, this);
    }
}

void
MessfQuery::Q1_eca (Ptr<Tuple> q1_ecaperiodic)
{
  RAPIDNET_LOG_INFO ("Q1_eca triggered");

  Ptr<RelationBase> result;

  result = GetRelation (TUPLE)->Join (
    q1_ecaperiodic,
    strlist ("tuple_attr1"),
    strlist ("q1_ecaperiodic_attr1"));

  result->Assign (Assignor::New ("UID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          VarExpr::New ("tuple_attr2"),
          VarExpr::New ("tuple_attr3")),
        VarExpr::New ("tuple_attr4")))));

  result->Assign (Assignor::New ("Time",
    FNow::New (
)));

  result->Assign (Assignor::New ("QID",
    FSha1::New (
      Operation::New (RN_PLUS,
        Operation::New (RN_PLUS,
          ValueExpr::New (StrValue::New ("")),
          VarExpr::New ("UID")),
        VarExpr::New ("Time")))));

  result = result->Project (
    PROVQUERY,
    strlist ("tuple_attr3",
      "QID",
      "UID",
      "q1_ecaperiodic_attr1",
      "tuple_attr3"),
    strlist ("provQuery_attr1",
      "provQuery_attr2",
      "provQuery_attr3",
      "provQuery_attr4",
      RN_DEST));

  Send (result);
}

void
MessfQuery::Q2_eca (Ptr<Tuple> pReturn)
{
  RAPIDNET_LOG_INFO ("Q2_eca triggered");

  Ptr<Tuple> result = pReturn;

  result = result->Project (
    RECORDS,
    strlist ("pReturn_attr1",
      "pReturn_attr2",
      "pReturn_attr3",
      "pReturn_attr4"),
    strlist ("records_attr1",
      "records_attr2",
      "records_attr3",
      "records_attr4"));

  Insert (result);
}

void
MessfQuery::Q3Eca0Ins (Ptr<Tuple> records)
{
  RAPIDNET_LOG_INFO ("Q3Eca0Ins triggered");

  Ptr<Tuple> result = records;

  result->Assign (Assignor::New ("Scores",
    FPCal::New (
      VarExpr::New ("records_attr4"))));

  result = result->Project (
    RESULTS,
    strlist ("records_attr1",
      "records_attr2",
      "records_attr3",
      "Scores"),
    strlist ("results_attr1",
      "results_attr2",
      "results_attr3",
      "results_attr4"));

  Insert (result);
}

void
MessfQuery::Q3Eca0Del (Ptr<Tuple> records)
{
  RAPIDNET_LOG_INFO ("Q3Eca0Del triggered");

  Ptr<Tuple> result = records;

  result->Assign (Assignor::New ("Scores",
    FPCal::New (
      VarExpr::New ("records_attr4"))));

  result = result->Project (
    RESULTS,
    strlist ("records_attr1",
      "records_attr2",
      "records_attr3",
      "Scores"),
    strlist ("results_attr1",
      "results_attr2",
      "results_attr3",
      "results_attr4"));

  Delete (result);
}

