/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef PINGPONGL4_H
#define PINGPONGL4_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace pingpongl4 {

class PingpongL4 : public RapidNetApplicationBase
{
public:
  static const string EPING;
  static const string EPINGPONGFINISH;
  static const string EPONG;
  static const string TLINK;

  static TypeId GetTypeId (void);

  PingpongL4 ();

  virtual ~PingpongL4 ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1Eca0Ins (Ptr<Tuple> tLink);

  virtual void R2_eca (Ptr<Tuple> ePing);

  virtual void R3_eca (Ptr<Tuple> ePong);

};

} // namespace pingpongl4
} // namespace rapidnet
} // namespace ns3

#endif // PINGPONGL4_H
