## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('emu-hsls-triggered', ['internet-stack'])
    module.source = [
        'emu-hsls-triggered.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'emu-hsls-triggered'
    headers.source = [
        'emu-hsls-triggered.h',
        'emu-hsls-triggered-helper.h',
        ]
