## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pktfwd-prov', ['internet-stack'])
    module.source = [
        'pktfwd-prov.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pktfwd-prov'
    headers.source = [
        'pktfwd-prov.h',
        'pktfwd-prov-helper.h',
        ]
