## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pathvector2', ['internet-stack'])
    module.source = [
        'pathvector2.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pathvector2'
    headers.source = [
        'pathvector2.h',
        'pathvector2-helper.h',
        ]
