## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('dsr', ['internet-stack'])
    module.source = [
        'dsr.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'dsr'
    headers.source = [
        'dsr.h',
        'dsr-helper.h',
        ]
