## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('discovery-epidemic', ['internet-stack'])
    module.source = [
        'discovery-epidemic.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'discovery-epidemic'
    headers.source = [
        'discovery-epidemic.h',
        'discovery-epidemic-helper.h',
        ]
