## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pathvector', ['internet-stack'])
    module.source = [
        'pathvector.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pathvector'
    headers.source = [
        'pathvector.h',
        'pathvector-helper.h',
        ]
