## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('pingpong', ['internet-stack'])
    module.source = [
        'pingpong.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'pingpong'
    headers.source = [
        'pingpong.h',
        'pingpong-helper.h',
        ]
