## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('sim-hsls-periodic', ['internet-stack'])
    module.source = [
        'sim-hsls-periodic.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'sim-hsls-periodic'
    headers.source = [
        'sim-hsls-periodic.h',
        'sim-hsls-periodic-helper.h',
        ]
