## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('mincost-query', ['internet-stack'])
    module.source = [
        'mincost-query.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'mincost-query'
    headers.source = [
        'mincost-query.h',
        'mincost-query-helper.h',
        ]
